// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://cloudopsmanager.com/terms/",
        "contact": {
            "name": "Cloud Ops Manager Team",
            "email": "team@cloudopsmanager.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/signin": {
            "post": {
                "description": "Authenticates a user and returns tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign in",
                "parameters": [
                    {
                        "description": "Sign in request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Registers a new user with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up a new user",
                "parameters": [
                    {
                        "description": "Sign up request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API. Used for load balancer health checks and monitoring purposes.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Service is healthy and operational",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/provision": {
            "post": {
                "description": "Submits a new resource provisioning request to be processed asynchronously. The request is validated and queued for processing via SQS.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Submit a resource provisioning request",
                "parameters": [
                    {
                        "description": "Resource provisioning request",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Resource"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Request accepted for processing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to process request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "id_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "model.Resource": {
            "description": "Cloud resource provisioning request",
            "type": "object",
            "required": [
                "cloud_provider",
                "id",
                "requested_by",
                "resource_type",
                "specification",
                "status"
            ],
            "properties": {
                "cloud_provider": {
                    "description": "Cloud provider where the resource will be provisioned",
                    "type": "string",
                    "enum": [
                        "AWS",
                        "Azure",
                        "GCP"
                    ],
                    "example": "AWS"
                },
                "id": {
                    "description": "Unique identifier for the resource",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "vm-001"
                },
                "requested_by": {
                    "description": "Username or identifier of the person who requested the resource",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "rafael"
                },
                "resource_type": {
                    "description": "Type of cloud resource to provision",
                    "type": "string",
                    "enum": [
                        "VM",
                        "RDS",
                        "S3",
                        "Lambda",
                        "VPC",
                        "ELB"
                    ],
                    "example": "VM"
                },
                "specification": {
                    "description": "Detailed specification of the resource configuration",
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1,
                    "example": "t2.micro"
                },
                "status": {
                    "description": "Current status of the resource provisioning request",
                    "type": "string",
                    "enum": [
                        "pending",
                        "in_progress",
                        "completed",
                        "failed"
                    ],
                    "example": "pending"
                }
            }
        },
        "model.SignInRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.SignUpRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Resource provisioning operations",
            "name": "resources"
        },
        {
            "description": "Health check operations",
            "name": "health"
        },
        {
            "description": "Authentication operations",
            "name": "auth"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:5000",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Cloud Ops Manager - Provisioner API",
	Description:      "The Cloud Ops Manager Provisioner API provides endpoints for managing cloud resource provisioning requests. This API accepts provisioning requests and queues them for asynchronous processing via SQS.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
