FROM golang:1.24

RUN useradd -m -u 1000 consumeruser
USER consumeruser

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /usr/src/app/bin/resource-provisioner-consumer ./cmd

CMD ["/usr/src/app/bin/resource-provisioner-consumer"]