project      = "internal-developer-platform"
environment  = "dev"
aws_region   = "us-east-1"
service_name = "resource-provisioner-api"
app_version  = "1.0.0"
api_version  = "v1"

cluster_name                       = "internal-developer-platform-cluster"
task_family                        = "resource-provisioner-api-task"
task_cpu                           = 512
task_memory                        = 1024
desired_count                      = 1
container_port                     = 8080
app_image_tag                      = "latest"
deployment_maximum_percent         = 200
deployment_minimum_healthy_percent = 50
platform_version                   = "1.4.0"
force_new_deployment               = true
assign_public_ip                   = false

nlb_name              = "idp-nlb"
internal              = true
load_balancer_type    = "network"
target_group_name     = "idp-tg-8080"
target_group_protocol = "TCP"
target_type           = "ip"
health_check_enabled  = true
health_check_protocol = "TCP"
health_check_port     = "traffic-port"
health_check_interval = 30
health_check_timeout  = 6
healthy_threshold     = 3
unhealthy_threshold   = 3
listener_port         = 80
listener_protocol     = "TCP"
listener_action_type  = "forward"

api_gateway_name                 = "internal-developer-platform-api"
api_gateway_description          = "Internal Developer Platform Provisioner API Gateway"
api_gateway_stage_name           = "dev"
api_gateway_auto_deploy          = true
vpc_link_name                    = "internal-developer-platform-vpc-link"
integration_timeout_ms           = 29000
throttle_rate_limit              = 1000
throttle_burst_limit             = 2000
cors_allow_credentials           = false
cors_allow_headers               = ["content-type", "x-amz-date", "authorization", "x-api-key", "x-amz-security-token"]
cors_allow_methods               = ["GET", "POST", "OPTIONS"]
cors_allow_origins               = ["*"]
cors_expose_headers              = []
cors_max_age                     = 86400
api_gateway_log_retention_days   = 7
api_gateway_logging_level        = "INFO"
api_gateway_metrics_enabled      = true
api_gateway_data_trace_enabled   = false
api_gateway_xray_tracing_enabled = true

# WAF Configuration
waf_rate_limit_requests   = 2000
waf_max_request_body_size = 10240
waf_common_rules_excluded = []
waf_enable_logging        = true
waf_log_retention_days    = 7

lambda_function_name              = "provisioner-api-datadog-forwarder"
lambda_runtime                    = "python3.9"
lambda_timeout                    = 120
lambda_memory_size                = 1024
archive_type                      = "zip"
archive_output_path_prefix        = "."
iam_role_name_suffix              = "-role"
lambda_basic_execution_policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
additional_policy_name_suffix     = "-additional-policy"
permission_statement_id           = "AllowExecutionFromCloudWatchLogs"
permission_action                 = "lambda:InvokeFunction"
permission_principal              = "logs.amazonaws.com"
log_group_name_prefix             = "/aws/lambda"

queue_name                = "provisioner_queue"
delay_seconds             = 0
max_message_size          = 262144
message_retention_seconds = 345600
receive_wait_time_seconds = 20
ssm_parameter_name        = "/INTERNAL_DEVELOPER_PLATFORM/PROVISIONER_QUEUE_URL"
ssm_parameter_type        = "String"
