services:
  internal-developer-platform-api:
    container_name: internal-developer-platform-api
    build:
      args:
        - GO_VERSION=${GO_VERSION:-1.25}
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=local
      - PORT=5000
    networks:
      - public-network
      - internal-network
    restart: on-failure