# ---- Build stage ----
FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/cloud-ops-manager-api ./cmd/server

# ---- Minimal runtime stage ----
FROM gcr.io/distroless/static:nonroot

WORKDIR /app
COPY --from=builder /app/cloud-ops-manager-api .

ENTRYPOINT ["/app/cloud-ops-manager-api"]