FROM golang:1.24

RUN useradd -m -u 1000 apiuser
USER apiuser

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /usr/src/app/bin/resource-provisioner-api ./cmd/server

CMD ["/usr/src/app/bin/resource-provisioner-api"]